import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

/**
 * Read-only portfolio content. Every table is seeded from
 * `migrations/9999_seed_portfolio.sql` (generated by `scripts/build-seed.ts`
 * from `scripts/portfolio-data.json`) — the worker never writes.
 *
 * Ids are the Mongo `_id`s carried over verbatim (slugs for experiences and
 * works, ObjectId hex for the rest) because the frontend keys on them.
 *
 * JSON columns rather than child tables wherever the frontend reads the value
 * whole and nothing filters or joins on it — `works`, `gradient`, `skills`.
 */

export type Gradient = { from: string; to: string };

/** Employment types the frontend styles by. */
export const EXPERIENCE_TYPES = [
  "FULL_TIME",
  "PART_TIME",
  "CONTRACT",
  "FREELANCE",
] as const;

export type ExperienceType = (typeof EXPERIENCE_TYPES)[number];

export const experiences = sqliteTable("experiences", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  role: text("role").notNull(),
  // ISO dates as text. Null `work_end` = current position; the service sorts on it.
  workStart: text("work_start").notNull(),
  workEnd: text("work_end"),
  location: text("location").notNull(),
  description: text("description").notNull(),
  type: text("type", { enum: EXPERIENCE_TYPES }).notNull(),
  // Ids into `works`. Read whole by the experience card, never joined.
  works: text("works", { mode: "json" })
    .$type<string[]>()
    .notNull()
    .default([]),
  gradient: text("gradient", { mode: "json" }).$type<Gradient>().notNull(),
});

export type ExperienceRow = typeof experiences.$inferSelect;

export const WORK_TYPES = ["MOBILE", "WEB", "MULTI_PLATFORM"] as const;

export type WorkType = (typeof WORK_TYPES)[number];

export const works = sqliteTable("works", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  descriptionShort: text("description_short").notNull(),
  descriptionLong: text("description_long").notNull(),
  icon: text("icon").notNull().default(""),
  // Empty until store enrichment fills it at read time.
  category: text("category").notNull().default(""),
  type: text("type", { enum: WORK_TYPES }).notNull(),
  appStoreId: text("app_store_id"),
  playStoreId: text("play_store_id"),
  // 0/1 — SQLite has no boolean. Converted in `toWork`.
  isInternal: integer("is_internal").notNull().default(0),
  featured: integer("featured").notNull().default(0),
  // Slug into `experiences`. Not a FK: a work can predate/outlive its employer row.
  companyId: text("company_id"),
  technologies: text("technologies", { mode: "json" })
    .$type<string[]>()
    .notNull()
    .default([]),
  // Store rating, fractional. Seeded 0; enrichment overrides at read time.
  rating: real("rating").notNull().default(0),
  screenshots: text("screenshots", { mode: "json" })
    .$type<string[]>()
    .notNull()
    .default([]),
  webUrls: text("web_urls", { mode: "json" }).$type<string[]>(),
  sourceCode: text("source_code"),
  googleGroupUrl: text("google_group_url"),
});

export type WorkRow = typeof works.$inferSelect;

export const educations = sqliteTable("educations", {
  id: text("id").primaryKey(),
  schoolName: text("school_name").notNull(),
  // "Sep 2022" style, as authored. Parsed with `new Date()` for sorting only.
  startDate: text("start_date").notNull(),
  endDate: text("end_date").notNull(),
  degreeName: text("degree_name").notNull().default(""),
  notes: text("notes").notNull().default(""),
  activities: text("activities").notNull().default(""),
});

export type EducationRow = typeof educations.$inferSelect;

export const certifications = sqliteTable("certifications", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  issuer: text("issuer").notNull(),
  date: text("date").notNull(),
  credentialId: text("credential_id"),
  link: text("link"),
});

export type CertificationRow = typeof certifications.$inferSelect;

export const PROFICIENCIES = [
  "Beginner",
  "Intermediate",
  "Advanced",
  "Expert",
] as const;

export type Proficiency = (typeof PROFICIENCIES)[number];

/** One skill inside a category's `skills` JSON. */
export type SkillJson = {
  name: string;
  proficiency: Proficiency;
  description: string;
};

// A category with its skills inline: the API returns them nested and the one
// filtered read (`/skills/category/:title`) still returns a whole category.
export const skillCategories = sqliteTable("skill_categories", {
  id: text("id").primaryKey(),
  title: text("title").notNull().unique(),
  icon: text("icon").notNull(),
  skills: text("skills", { mode: "json" })
    .$type<SkillJson[]>()
    .notNull()
    .default([]),
});

export type SkillCategoryRow = typeof skillCategories.$inferSelect;

// Exactly one row today (`type = 'profile'`); `GET /api/me` reads it.
export const profile = sqliteTable("profile", {
  id: text("id").primaryKey(),
  type: text("type").notNull(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  headline: text("headline").notNull(),
  summary: text("summary").notNull(),
  industry: text("industry"),
  location: text("location"),
  birthDate: text("birth_date"),
  website: text("website"),
  twitterHandles: text("twitter_handles", { mode: "json" })
    .$type<string[]>()
    .notNull()
    .default([]),
});

export type ProfileRow = typeof profile.$inferSelect;
