/**
 * Seed generator. Reads `scripts/portfolio-data.json` (the portfolio content,
 * exported once from the old Mongo database and edited in place since) and
 * writes `migrations/9999_seed_portfolio.sql`. Run it after any content edit:
 *
 *   bun run build:seed
 *
 * Column order and names follow `src/db/schema.ts`. Idempotent: every statement
 * is `INSERT OR REPLACE`, so a regenerated seed overwrites rather than fails.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DATA_JSON = join(ROOT, "scripts/portfolio-data.json");
// Numbered high on purpose: wrangler applies migrations in lexicographic order,
// so the seed always lands after whatever schema migration drizzle-kit generates
// next, and its number can never collide with drizzle's incrementing ones.
const SEED_SQL = join(ROOT, "migrations/9999_seed_portfolio.sql");

type Gradient = { from: string; to: string };

type Data = {
  profile: {
    id: string;
    type: string;
    firstName: string;
    lastName: string;
    headline: string;
    summary: string;
    industry: string | null;
    location: string | null;
    birthDate: string | null;
    website: string | null;
    twitterHandles: string[];
  }[];
  experiences: {
    id: string;
    name: string;
    role: string;
    workStart: string;
    workEnd: string | null;
    location: string;
    description: string;
    type: string;
    works: string[];
    gradient: Gradient;
  }[];
  works: {
    id: string;
    name: string;
    description: { short: string; long: string };
    icon: string;
    category: string;
    type: string;
    appStoreId: string | null;
    playStoreId: string | null;
    isInternal: boolean;
    featured: boolean;
    companyId: string | null;
    technologies: string[];
    rating: number;
    screenshots: string[];
    webUrls: string[] | null;
    sourceCode: string | null;
    googleGroupUrl: string | null;
  }[];
  educations: {
    id: string;
    schoolName: string;
    startDate: string;
    endDate: string;
    degreeName: string;
    notes: string;
    activities: string;
  }[];
  certifications: {
    id: string;
    name: string;
    issuer: string;
    date: string;
    credentialId: string | null;
    link: string | null;
  }[];
  skillCategories: {
    id: string;
    title: string;
    icon: string;
    skills: { name: string; proficiency: string; description: string }[];
  }[];
};

type SqlValue = string | number | boolean | null | object;

/** One SQL literal. Objects/arrays become JSON text, booleans 0/1. */
function lit(value: SqlValue): string {
  if (value === null) {
    return "NULL";
  }
  if (typeof value === "number") {
    return String(value);
  }
  if (typeof value === "boolean") {
    return value ? "1" : "0";
  }
  const text = typeof value === "string" ? value : JSON.stringify(value);
  return `'${text.replace(/'/g, "''")}'`;
}

/** `INSERT OR REPLACE INTO <table> (<cols>) VALUES (<row>);` for each row. */
function insertAll(
  table: string,
  columns: string[],
  rows: SqlValue[][]
): string[] {
  const lines: string[] = [];
  for (const row of rows) {
    lines.push(
      `INSERT OR REPLACE INTO ${table} (${columns.join(", ")}) VALUES`,
      `  (${row.map(lit).join(", ")});`
    );
  }
  lines.push("");
  return lines;
}

function main(): void {
  const data = JSON.parse(readFileSync(DATA_JSON, "utf8")) as Data;

  const lines: string[] = [
    "-- Seed the portfolio content. Generated by scripts/build-seed.ts —",
    "-- edit scripts/portfolio-data.json and re-run `bun run build:seed` instead",
    "-- of editing this file. Idempotent: re-applying overwrites rather than",
    "-- failing, so corrected content can ship as a regenerated seed.",
    "",
  ];

  lines.push(
    ...insertAll(
      "profile",
      [
        "id",
        "type",
        "first_name",
        "last_name",
        "headline",
        "summary",
        "industry",
        "location",
        "birth_date",
        "website",
        "twitter_handles",
      ],
      data.profile.map((p) => [
        p.id,
        p.type,
        p.firstName,
        p.lastName,
        p.headline,
        p.summary,
        p.industry,
        p.location,
        p.birthDate,
        p.website,
        p.twitterHandles,
      ])
    )
  );

  lines.push(
    ...insertAll(
      "experiences",
      [
        "id",
        "name",
        "role",
        "work_start",
        "work_end",
        "location",
        "description",
        "type",
        "works",
        "gradient",
      ],
      data.experiences.map((e) => [
        e.id,
        e.name,
        e.role,
        e.workStart,
        e.workEnd,
        e.location,
        e.description,
        e.type,
        e.works,
        e.gradient,
      ])
    )
  );

  lines.push(
    ...insertAll(
      "works",
      [
        "id",
        "name",
        "description_short",
        "description_long",
        "icon",
        "category",
        "type",
        "app_store_id",
        "play_store_id",
        "is_internal",
        "featured",
        "company_id",
        "technologies",
        "rating",
        "screenshots",
        "web_urls",
        "source_code",
        "google_group_url",
      ],
      data.works.map((w) => [
        w.id,
        w.name,
        w.description.short,
        w.description.long,
        w.icon,
        w.category,
        w.type,
        w.appStoreId,
        w.playStoreId,
        w.isInternal,
        w.featured,
        w.companyId,
        w.technologies,
        w.rating,
        w.screenshots,
        w.webUrls,
        w.sourceCode,
        w.googleGroupUrl,
      ])
    )
  );

  lines.push(
    ...insertAll(
      "educations",
      [
        "id",
        "school_name",
        "start_date",
        "end_date",
        "degree_name",
        "notes",
        "activities",
      ],
      data.educations.map((e) => [
        e.id,
        e.schoolName,
        e.startDate,
        e.endDate,
        e.degreeName,
        e.notes,
        e.activities,
      ])
    )
  );

  lines.push(
    ...insertAll(
      "certifications",
      ["id", "name", "issuer", "date", "credential_id", "link"],
      data.certifications.map((c) => [
        c.id,
        c.name,
        c.issuer,
        c.date,
        c.credentialId,
        c.link,
      ])
    )
  );

  lines.push(
    ...insertAll(
      "skill_categories",
      ["id", "title", "icon", "skills"],
      data.skillCategories.map((s) => [s.id, s.title, s.icon, s.skills])
    )
  );

  writeFileSync(SEED_SQL, lines.join("\n"));

  const counts = Object.entries(data)
    .map(([table, rows]) => `${rows.length} ${table}`)
    .join(", ");
  process.stdout.write(`${counts}\nseed → ${SEED_SQL}\n`);
}

main();
